# Generated by Django 4.2.7 on 2026-01-28 18:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Unique staff identifier', max_length=20, unique=True)),
                ('name', models.CharField(help_text="Staff member's full name", max_length=100)),
                ('role', models.CharField(choices=[('warden', 'Warden'), ('security', 'Security'), ('admin', 'Administrator'), ('maintenance', 'Maintenance')], help_text='Staff role/position', max_length=20)),
                ('permissions', models.JSONField(default=dict, help_text='Role-based permissions')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether staff member is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique student identifier', max_length=20, unique=True)),
                ('name', models.CharField(help_text="Student's full name", max_length=100)),
                ('room_number', models.CharField(help_text='Room number assignment', max_length=10)),
                ('block', models.CharField(help_text='Hostel block (e.g., A, B, C)', max_length=5)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True)),
                ('violation_count', models.IntegerField(default=0, help_text='Number of policy violations', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_violation_date', models.DateTimeField(blank=True, help_text='Date of most recent violation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.TextField(help_text='Original message content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed', models.BooleanField(default=False, help_text='Whether message has been processed')),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence score (0.0-1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('extracted_intent', models.JSONField(blank=True, help_text='Extracted intent and entities', null=True)),
                ('response_sent', models.BooleanField(default=False, help_text='Whether response was sent to student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.student')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('guest_name', models.CharField(help_text='Name of the guest', max_length=100)),
                ('guest_phone', models.CharField(blank=True, help_text='Guest contact number', max_length=15, null=True)),
                ('start_date', models.DateTimeField(help_text='Guest arrival date and time')),
                ('end_date', models.DateTimeField(help_text='Guest departure date and time')),
                ('purpose', models.TextField(blank=True, help_text='Purpose of visit', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('auto_approved', models.BooleanField(default=False, help_text='Whether request was auto-approved')),
                ('approval_reason', models.TextField(blank=True, help_text='Reason for approval/rejection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_guests', to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_requests', to='core.student')),
            ],
            options={
                'db_table': 'guest_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('message_processing', 'Message Processing'), ('guest_approval', 'Guest Approval'), ('absence_approval', 'Absence Approval'), ('rule_validation', 'Rule Validation'), ('conflict_detection', 'Conflict Detection'), ('staff_query', 'Staff Query'), ('system_action', 'System Action')], help_text='Type of action performed', max_length=50)),
                ('entity_type', models.CharField(help_text='Type of entity affected', max_length=50)),
                ('entity_id', models.CharField(help_text='ID of the affected entity', max_length=100)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('processed', 'Processed'), ('failed', 'Failed')], help_text='Decision made', max_length=20)),
                ('reasoning', models.TextField(help_text='Detailed reasoning for the decision')),
                ('confidence_score', models.FloatField(help_text='Confidence score for the decision', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('rules_applied', models.JSONField(default=list, help_text='List of rules applied in decision')),
                ('user_id', models.CharField(help_text='ID of user who triggered the action', max_length=50)),
                ('user_type', models.CharField(default='student', help_text='Type of user (student/staff)', max_length=20)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata for the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action_type', 'timestamp'], name='audit_logs_action__11f9f1_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['user_id', 'timestamp'], name='audit_logs_user_id_88267f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AbsenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateTimeField(help_text='Start date of absence')),
                ('end_date', models.DateTimeField(help_text='End date of absence')),
                ('reason', models.TextField(help_text='Reason for absence')),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact during absence', max_length=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('auto_approved', models.BooleanField(default=False, help_text='Whether request was auto-approved')),
                ('approval_reason', models.TextField(blank=True, help_text='Reason for approval/rejection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_absences', to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_records', to='core.student')),
            ],
            options={
                'db_table': 'absence_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
