# Generated by Django 4.2.7 on 2026-01-28 20:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('message_processing', 'Message Processing'), ('guest_approval', 'Guest Approval'), ('absence_approval', 'Absence Approval'), ('maintenance_approval', 'Maintenance Approval'), ('rule_validation', 'Rule Validation'), ('conflict_detection', 'Conflict Detection'), ('staff_query', 'Staff Query'), ('system_action', 'System Action')], help_text='Type of action performed', max_length=50),
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('room_number', models.CharField(help_text='Room where maintenance is needed', max_length=10)),
                ('issue_type', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC/Air Conditioning'), ('furniture', 'Furniture'), ('cleaning', 'Cleaning'), ('other', 'Other')], help_text='Type of maintenance issue', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('auto_approved', models.BooleanField(default=False, help_text='Whether request was auto-approved')),
                ('estimated_completion', models.DateTimeField(blank=True, help_text='Estimated completion date', null=True)),
                ('actual_completion', models.DateTimeField(blank=True, help_text='Actual completion date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from maintenance staff', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='core.student')),
            ],
            options={
                'db_table': 'maintenance_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
