# Generated by Django 4.2.7 on 2026-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_authentication_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='temp@staff.com', help_text='Staff email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='temp@example.com', help_text="Student's email address", max_length=254, unique=True),
        ),
    ]
