# Generated by Django 4.2.7 on 2026-02-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conversationcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestrequest',
            name='relationship',
            field=models.CharField(choices=[('parent', 'Parent'), ('sibling', 'Sibling'), ('relative', 'Relative'), ('guardian', 'Guardian'), ('friend', 'Friend'), ('other', 'Other')], default='other', help_text='Relationship with the guest', max_length=20),
        ),
    ]
