# Generated by Django 4.2.7 on 2026-01-29 19:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_staff_email_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pass_number', models.CharField(help_text='Unique pass number for verification', max_length=20, unique=True)),
                ('from_date', models.DateField(help_text='Leave start date')),
                ('to_date', models.DateField(help_text='Leave end date')),
                ('total_days', models.IntegerField(help_text='Total number of leave days')),
                ('reason', models.TextField(help_text='Reason for leave')),
                ('approval_type', models.CharField(choices=[('auto', 'Auto-Approved'), ('manual', 'Manually Approved')], help_text='Type of approval', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', help_text='Current status of the pass', max_length=20)),
                ('pdf_generated', models.BooleanField(default=False, help_text='Whether PDF has been generated')),
                ('pdf_path', models.CharField(blank=True, help_text='Path to generated PDF file', max_length=255, null=True)),
                ('verification_code', models.CharField(help_text='Short verification code for security', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_pass', to='core.absencerecord')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_passes', to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_passes', to='core.student')),
            ],
            options={
                'db_table': 'digital_passes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('message_processing', 'Message Processing'), ('guest_approval', 'Guest Approval'), ('absence_approval', 'Absence Approval'), ('maintenance_approval', 'Maintenance Approval'), ('rule_validation', 'Rule Validation'), ('conflict_detection', 'Conflict Detection'), ('staff_query', 'Staff Query'), ('system_action', 'System Action'), ('pass_generation', 'Pass Generation'), ('security_verification', 'Security Verification')], help_text='Type of action performed', max_length=50),
        ),
        migrations.CreateModel(
            name='SecurityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('allowed_to_leave', 'Allowed to Leave'), ('restricted', 'Restricted'), ('returned', 'Returned')], help_text='Current security status', max_length=20)),
                ('verified_by', models.CharField(blank=True, help_text='Security personnel who verified', max_length=100, null=True)),
                ('verification_time', models.DateTimeField(blank=True, help_text='Time of verification', null=True)),
                ('gate_exit_time', models.DateTimeField(blank=True, help_text='Time student left through gate', null=True)),
                ('gate_entry_time', models.DateTimeField(blank=True, help_text='Time student returned through gate', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional security notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digital_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_records', to='core.digitalpass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_records', to='core.student')),
            ],
            options={
                'db_table': 'security_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='security_re_student_3f4fb9_idx'), models.Index(fields=['digital_pass'], name='security_re_digital_d84498_idx'), models.Index(fields=['verification_time'], name='security_re_verific_989f1d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='digitalpass',
            index=models.Index(fields=['pass_number'], name='digital_pas_pass_nu_e3be0f_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalpass',
            index=models.Index(fields=['student', 'status'], name='digital_pas_student_84bf16_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalpass',
            index=models.Index(fields=['from_date', 'to_date'], name='digital_pas_from_da_65e325_idx'),
        ),
    ]
