# Generated by Django 4.2.7 on 2026-01-31 05:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_digitalpass_alter_auditlog_action_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.CharField(help_text='User identifier', max_length=50)),
                ('user_type', models.CharField(default='student', help_text='Type of user (student/staff)', max_length=20)),
                ('conversation_id', models.CharField(help_text='Unique conversation identifier', max_length=200, unique=True)),
                ('intent_history', models.JSONField(default=list, help_text='History of intents in this conversation')),
                ('last_message_id', models.CharField(blank=True, help_text='ID of the last message processed', max_length=200)),
                ('pending_clarifications', models.JSONField(default=list, help_text='List of pending clarification fields')),
                ('context_data', models.JSONField(default=dict, help_text='Conversation context data (e.g., leave_request_data)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_context', to='core.student')),
            ],
            options={
                'db_table': 'conversation_contexts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user_id', 'updated_at'], name='conversatio_user_id_0789c1_idx'), models.Index(fields=['conversation_id'], name='conversatio_convers_a6e4ed_idx')],
            },
        ),
    ]
