# Generated by Django 4.2.7 on 2026-02-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_guest_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
    ]
