# Generated by Django 4.2.7 on 2026-03-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_student_roll_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
